// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

BridgeCalendarDraft? bykcCalendarDraft({
  required String title,
  String? location,
  String? start,
  String? end,
  String? selectStart,
  required bool reminder,
}) => RustLib.instance.api.crateApiCalendarBykcCalendarDraft(
  title: title,
  location: location,
  start: start,
  end: end,
  selectStart: selectStart,
  reminder: reminder,
);

bool calendarOverlaps({
  required PlatformInt64 start,
  required PlatformInt64 end,
  required PlatformInt64 otherStart,
  required PlatformInt64 otherEnd,
}) => RustLib.instance.api.crateApiCalendarCalendarOverlaps(
  start: start,
  end: end,
  otherStart: otherStart,
  otherEnd: otherEnd,
);

class BridgeCalendarDraft {
  final String title;
  final String location;
  final String description;
  final PlatformInt64 startMs;
  final PlatformInt64 endMs;
  final int? reminderMinutes;

  const BridgeCalendarDraft({
    required this.title,
    required this.location,
    required this.description,
    required this.startMs,
    required this.endMs,
    this.reminderMinutes,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      location.hashCode ^
      description.hashCode ^
      startMs.hashCode ^
      endMs.hashCode ^
      reminderMinutes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCalendarDraft &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          location == other.location &&
          description == other.description &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          reminderMinutes == other.reminderMinutes;
}
