// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'read.dart';
import 'write.dart';

// These functions are ignored because they are not marked as `pub`: `catch_panic`, `disposed_error`, `from_core`, `from_routed`, `local`, `map_login_outcome`, `map_preparation`, `map_profile`, `map_route_login`, `map_route`, `map_safe_error`, `panic_error`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeClient>>
abstract class BridgeClient implements RustOpaqueInterface {
  /// 校验持久化认证状态。
  ///
  /// # Errors
  ///
  /// 客户端已销毁或 Core 无法读取认证状态时返回安全错误。
  Future<BridgeLoginOutcome> authStatus();

  Future<BridgeRoutedBykcChosenCourses> bykcChosenCourses();

  Future<BridgeRoutedBykcCourse> bykcCourseDetail({required PlatformInt64 id});

  Future<BridgeRoutedBykcCourses> bykcCourses({
    required int page,
    required int size,
    required bool all,
  });

  Future<BridgeRoutedBykcProfile> bykcProfile();

  Future<BridgeRoutedBykcStatistics> bykcStatistics();

  Future<BridgeRoutedCgyyDayInfo> cgyyDayInfo({
    required int siteId,
    required String date,
  });

  Future<BridgeRoutedCgyyLockCode> cgyyLockCode();

  Future<BridgeRoutedCgyyOrder> cgyyOrderDetail({required int id});

  /// 在调用方指定的已认证路线读取场馆订单详情，不执行 Auto 探测或回退。
  Future<BridgeCallerPinnedCgyyOrder> cgyyOrderDetailOnRoute({
    required BridgeConnectionMode route,
    required int id,
  });

  Future<BridgeRoutedCgyyOrders> cgyyOrders({
    required int page,
    required int size,
  });

  /// 在调用方指定的已认证路线读取场馆订单，不执行 Auto 探测或回退。
  Future<BridgeCallerPinnedCgyyOrders> cgyyOrdersOnRoute({
    required BridgeConnectionMode route,
    required int page,
    required int size,
  });

  Future<BridgeRoutedCgyyPurposeTypes> cgyyPurposeTypes();

  Future<BridgeRoutedCgyySites> cgyySites();

  Future<BridgeRoutedClassroomQuery> classroomSearch({
    required int campus,
    required String date,
  });

  Future<BridgeWriteCommitResult> commitWrite({required String intentId});

  /// 返回 bridge 合同版本。
  int contractVersion();

  /// 放弃一个尚未提交的写入意图。
  ///
  /// 已不存在的标识按幂等成功处理；已经进入 commit 的请求不会被异步中断。
  Future<void> discardWriteIntent({required String intentId});

  /// 幂等销毁 Core client。
  ///
  /// # Errors
  ///
  /// 当前实现不会返回错误；保留 `Result` 以便未来生命周期清理失败时维持稳定 ABI。
  @override
  Future<void> dispose();

  Future<BridgeRoutedEvaluation> evaluationAll();

  /// 在调用方指定的已认证路线读取评教课程，不执行 Auto 探测或回退。
  Future<BridgeCallerPinnedEvaluation> evaluationAllOnRoute({
    required BridgeConnectionMode route,
  });

  Future<BridgeRoutedExamArrangement> examArrangement({required String term});

  Future<BridgeRoutedTerms> examTerms();

  Future<BridgeRoutedGradeOverview> gradeOverview();

  Future<BridgeRoutedGrades> grades({required String term});

  Future<BridgeRoutedJudgeAssignmentDetail> judgeAssignment({
    required String courseId,
    required String assignmentId,
  });

  Future<BridgeRoutedJudgeAssignmentDetails> judgeAssignmentDetails({
    required List<BridgeJudgeAssignmentKey> keys,
  });

  Future<BridgeRoutedJudgeSummaries> judgeAssignments({
    required bool includeExpired,
  });

  Future<BridgeRoutedLibBookAreaDetail> libbookAreaDetail({
    required String areaId,
  });

  Future<BridgeRoutedLibBookAreas> libbookAreas({
    required String premisesId,
    String? storeyId,
    required String day,
  });

  Future<BridgeRoutedLibBookBookings> libbookBookings({
    required int page,
    required int limit,
  });

  Future<BridgeRoutedLibBookLibraries> libbookLibraries({required String day});

  Future<BridgeRoutedLibBookSeats> libbookSeats({
    required String areaId,
    required String day,
    required String startTime,
    required String endTime,
  });

  /// 提交双路线账号密码。
  ///
  /// # Errors
  ///
  /// 输入为空、客户端已销毁或 Core 登录失败时返回安全错误。
  Future<BridgeLoginOutcome> login({
    required String username,
    required String password,
  });

  /// 清理 Core Session 并执行尽力远端注销。
  ///
  /// # Errors
  ///
  /// 客户端已销毁或 Core 注销失败时返回安全错误。
  Future<void> logout();

  /// 打开应用私有目录中的 Core client。
  static BridgeClient open({required String configDir}) =>
      RustLib.instance.api.crateApiClientBridgeClientOpen(configDir: configDir);

  Future<BridgeWriteIntent> prepareBykcDeselectCourse({
    required BridgeBykcCourseRequest request,
  });

  Future<BridgeWriteIntent> prepareBykcSelectCourse({
    required BridgeBykcCourseRequest request,
  });

  Future<BridgeWriteIntent> prepareBykcSignCourse({
    required BridgeBykcSignCourseRequest request,
  });

  Future<BridgeWriteIntent> prepareCgyyCancelOrder({
    required BridgeCgyyCancelOrderRequest request,
  });

  Future<BridgeWriteIntent> prepareCgyySubmitReservation({
    required BridgeCgyySubmitReservationRequest request,
  });

  Future<BridgeWriteIntent> prepareEvaluationSubmitCourses({
    required BridgeEvaluationSubmitCoursesRequest request,
  });

  Future<BridgeWriteIntent> prepareLibbookCancelBooking({
    required BridgeLibbookCancelBookingRequest request,
  });

  Future<BridgeWriteIntent> prepareLibbookReserve({
    required BridgeLibbookReserveRequest request,
  });

  /// 准备两条路线的登录页状态。
  ///
  /// # Errors
  ///
  /// 客户端已销毁或 Core 无法准备路线时返回安全错误。
  Future<BridgeLoginPreparation> prepareLogin();

  Future<BridgeWriteIntent> prepareSigninPerform({
    required BridgeSigninPerformRequest request,
  });

  Future<BridgeWriteIntent> prepareYgdkSubmit({
    required BridgeYgdkSubmitRequest request,
  });

  /// 读取全局路线策略与已认证槽位。
  ///
  /// # Errors
  ///
  /// 客户端已销毁时返回安全错误。
  Future<BridgeRouteSettings> routeSettings();

  Future<BridgeRoutedTerms> scheduleTerms();

  Future<BridgeRoutedTodayClasses> scheduleToday();

  Future<BridgeRoutedWeeklySchedule> scheduleWeek({
    required String term,
    required int week,
  });

  Future<BridgeRoutedWeeks> scheduleWeeks({required String term});

  /// 保存新的全局策略、清除 feature override 并重开 Core client。
  ///
  /// # Errors
  ///
  /// 另一个 bridge 操作占用客户端、客户端已销毁、配置保存失败或重开失败时返回安全错误。
  Future<BridgeRouteSettings> setDefaultRoutePolicy({
    required BridgeRoutePolicy policy,
  });

  Future<BridgeRoutedSigninClasses> signinToday();

  Future<BridgeRoutedSpocAssignmentDetail> spocAssignment({
    required String assignmentId,
  });

  Future<BridgeRoutedSpocAssignments> spocAssignments();

  /// 获取必要的用户资料。
  ///
  /// # Errors
  ///
  /// 客户端已销毁、未认证或 Core 读取资料失败时返回安全错误。
  Future<BridgeRoutedUserProfile> userInfo();

  Future<BridgeRoutedYgdkOverview> ygdkOverview();

  /// 在调用方指定的已认证路线读取阳光打卡概览，不执行 Auto 探测或回退。
  Future<BridgeCallerPinnedYgdkOverview> ygdkOverviewOnRoute({
    required BridgeConnectionMode route,
  });

  Future<BridgeRoutedYgdkRecords> ygdkRecords({
    required int page,
    required int size,
  });

  /// 在调用方指定的已认证路线读取阳光打卡记录，不执行 Auto 探测或回退。
  Future<BridgeCallerPinnedYgdkRecords> ygdkRecordsOnRoute({
    required BridgeConnectionMode route,
    required int page,
    required int size,
  });
}

/// 当前连接路线。
enum BridgeConnectionMode { direct, webVpn }

/// Dart 可捕获的 typed 安全错误。
class BridgeError implements FrbException {
  final BridgeErrorCode code;
  final BridgeErrorKind kind;
  final bool retryable;
  final String message;
  final BridgeConnectionMode? resolvedRoute;

  const BridgeError({
    required this.code,
    required this.kind,
    required this.retryable,
    required this.message,
    this.resolvedRoute,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      kind.hashCode ^
      retryable.hashCode ^
      message.hashCode ^
      resolvedRoute.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          kind == other.kind &&
          retryable == other.retryable &&
          message == other.message &&
          resolvedRoute == other.resolvedRoute;
}

/// Core 与 bridge 共用的机器错误码。
enum BridgeErrorCode {
  invalidInput,
  authenticationRequired,
  invalidCredentials,
  passwordRiskConfirmationFailed,
  permissionDenied,
  networkError,
  timeout,
  upstreamUnavailable,
  upstreamChanged,
  parseError,
  internalError,
  clientDisposed,
  confirmationRequired,
  intentExpired,
  operationConflict,
  outcomeUnknown,
  unsupported,
}

/// bridge 对外的安全错误类别。
enum BridgeErrorKind {
  input,
  authentication,
  network,
  upstream,
  parse,
  internal,
}

/// 聚合登录结果。
class BridgeLoginOutcome {
  final BridgeLoginReadiness readiness;
  final List<BridgeRouteLoginResult> routes;
  final BridgeUserProfile? profile;

  const BridgeLoginOutcome({
    required this.readiness,
    required this.routes,
    this.profile,
  });

  @override
  int get hashCode => readiness.hashCode ^ routes.hashCode ^ profile.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLoginOutcome &&
          runtimeType == other.runtimeType &&
          readiness == other.readiness &&
          routes == other.routes &&
          profile == other.profile;
}

/// 两条路线登录准备结果。
class BridgeLoginPreparation {
  final List<BridgeRouteLoginResult> routes;

  const BridgeLoginPreparation({required this.routes});

  @override
  int get hashCode => routes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLoginPreparation &&
          runtimeType == other.runtimeType &&
          routes == other.routes;
}

/// 聚合登录状态。
enum BridgeLoginReadiness { allReady, partial, noneReady }

/// 网关探测三态结果。
enum BridgeNetworkState { campus, offCampus, unknown }

/// 一次 Core 路线决策的安全投影。
class BridgeRouteDecision {
  final BridgeRoutePolicy policy;
  final BridgeConnectionMode resolvedRoute;
  final BridgeNetworkState network;
  final BridgeConnectionMode initialRoute;
  final bool usedFallback;

  const BridgeRouteDecision({
    required this.policy,
    required this.resolvedRoute,
    required this.network,
    required this.initialRoute,
    required this.usedFallback,
  });

  @override
  int get hashCode =>
      policy.hashCode ^
      resolvedRoute.hashCode ^
      network.hashCode ^
      initialRoute.hashCode ^
      usedFallback.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRouteDecision &&
          runtimeType == other.runtimeType &&
          policy == other.policy &&
          resolvedRoute == other.resolvedRoute &&
          network == other.network &&
          initialRoute == other.initialRoute &&
          usedFallback == other.usedFallback;
}

/// 单条路线登录结果。
class BridgeRouteLoginResult {
  final BridgeConnectionMode route;
  final BridgeRouteLoginState state;
  final BridgeSafeError? error;

  const BridgeRouteLoginResult({
    required this.route,
    required this.state,
    this.error,
  });

  @override
  int get hashCode => route.hashCode ^ state.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRouteLoginResult &&
          runtimeType == other.runtimeType &&
          route == other.route &&
          state == other.state &&
          error == other.error;
}

/// 路线登录状态。
enum BridgeRouteLoginState { ready, failed }

/// 用户选择的路线策略。
enum BridgeRoutePolicy { auto, direct, webVpn }

/// 当前路线设置。
class BridgeRouteSettings {
  final BridgeRoutePolicy defaultPolicy;
  final List<BridgeConnectionMode> activeRoutes;

  const BridgeRouteSettings({
    required this.defaultPolicy,
    required this.activeRoutes,
  });

  @override
  int get hashCode => defaultPolicy.hashCode ^ activeRoutes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRouteSettings &&
          runtimeType == other.runtimeType &&
          defaultPolicy == other.defaultPolicy &&
          activeRoutes == other.activeRoutes;
}

/// 带路线决策的用户资料。
class BridgeRoutedUserProfile {
  final BridgeUserProfile data;
  final BridgeRouteDecision route;

  const BridgeRoutedUserProfile({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedUserProfile &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

/// 路线错误的安全投影。
class BridgeSafeError {
  final String code;
  final String kind;
  final bool retryable;
  final String message;

  const BridgeSafeError({
    required this.code,
    required this.kind,
    required this.retryable,
    required this.message,
  });

  @override
  int get hashCode =>
      code.hashCode ^ kind.hashCode ^ retryable.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSafeError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          kind == other.kind &&
          retryable == other.retryable &&
          message == other.message;
}

/// 用户资料白名单。
class BridgeUserProfile {
  final String? username;
  final String? name;
  final String? schoolId;
  final String? email;
  final String? phone;
  final String? idCardTypeName;

  const BridgeUserProfile({
    this.username,
    this.name,
    this.schoolId,
    this.email,
    this.phone,
    this.idCardTypeName,
  });

  @override
  int get hashCode =>
      username.hashCode ^
      name.hashCode ^
      schoolId.hashCode ^
      email.hashCode ^
      phone.hashCode ^
      idCardTypeName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeUserProfile &&
          runtimeType == other.runtimeType &&
          username == other.username &&
          name == other.name &&
          schoolId == other.schoolId &&
          email == other.email &&
          phone == other.phone &&
          idCardTypeName == other.idCardTypeName;
}
