// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'client.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `hash`

enum BridgeActionEligibility { allowed, denied, unknown }

class BridgeBykcChosenCourse {
  final PlatformInt64 id;
  final PlatformInt64 courseId;
  final String courseName;
  final String? coursePosition;
  final String? courseTeacher;
  final String? courseStartDate;
  final String? courseEndDate;
  final String? selectDate;
  final String? courseCancelEndDate;
  final BridgeBykcCourseCategory? category;
  final BridgeBykcCourseSubCategory? subCategory;
  final int? checkin;
  final int? score;
  final int? pass;
  final BridgeActionEligibility signEligibility;
  final BridgeActionEligibility signOutEligibility;
  final BridgeActionEligibility deselectEligibility;
  final BridgeBykcSignConfig? signConfig;
  final int? courseSignType;

  const BridgeBykcChosenCourse({
    required this.id,
    required this.courseId,
    required this.courseName,
    this.coursePosition,
    this.courseTeacher,
    this.courseStartDate,
    this.courseEndDate,
    this.selectDate,
    this.courseCancelEndDate,
    this.category,
    this.subCategory,
    this.checkin,
    this.score,
    this.pass,
    required this.signEligibility,
    required this.signOutEligibility,
    required this.deselectEligibility,
    this.signConfig,
    this.courseSignType,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      courseId.hashCode ^
      courseName.hashCode ^
      coursePosition.hashCode ^
      courseTeacher.hashCode ^
      courseStartDate.hashCode ^
      courseEndDate.hashCode ^
      selectDate.hashCode ^
      courseCancelEndDate.hashCode ^
      category.hashCode ^
      subCategory.hashCode ^
      checkin.hashCode ^
      score.hashCode ^
      pass.hashCode ^
      signEligibility.hashCode ^
      signOutEligibility.hashCode ^
      deselectEligibility.hashCode ^
      signConfig.hashCode ^
      courseSignType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBykcChosenCourse &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          courseId == other.courseId &&
          courseName == other.courseName &&
          coursePosition == other.coursePosition &&
          courseTeacher == other.courseTeacher &&
          courseStartDate == other.courseStartDate &&
          courseEndDate == other.courseEndDate &&
          selectDate == other.selectDate &&
          courseCancelEndDate == other.courseCancelEndDate &&
          category == other.category &&
          subCategory == other.subCategory &&
          checkin == other.checkin &&
          score == other.score &&
          pass == other.pass &&
          signEligibility == other.signEligibility &&
          signOutEligibility == other.signOutEligibility &&
          deselectEligibility == other.deselectEligibility &&
          signConfig == other.signConfig &&
          courseSignType == other.courseSignType;
}

class BridgeBykcCourse {
  final PlatformInt64 id;
  final String courseName;
  final String? coursePosition;
  final String? courseTeacher;
  final String? courseStartDate;
  final String? courseEndDate;
  final String? courseSelectStartDate;
  final String? courseSelectEndDate;
  final String? courseCancelEndDate;
  final int? courseMaxCount;
  final int? courseCurrentCount;
  final BridgeBykcCourseStatus status;
  final bool? selected;
  final BridgeActionEligibility selectEligibility;
  final BridgeActionEligibility deselectEligibility;

  const BridgeBykcCourse({
    required this.id,
    required this.courseName,
    this.coursePosition,
    this.courseTeacher,
    this.courseStartDate,
    this.courseEndDate,
    this.courseSelectStartDate,
    this.courseSelectEndDate,
    this.courseCancelEndDate,
    this.courseMaxCount,
    this.courseCurrentCount,
    required this.status,
    this.selected,
    required this.selectEligibility,
    required this.deselectEligibility,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      courseName.hashCode ^
      coursePosition.hashCode ^
      courseTeacher.hashCode ^
      courseStartDate.hashCode ^
      courseEndDate.hashCode ^
      courseSelectStartDate.hashCode ^
      courseSelectEndDate.hashCode ^
      courseCancelEndDate.hashCode ^
      courseMaxCount.hashCode ^
      courseCurrentCount.hashCode ^
      status.hashCode ^
      selected.hashCode ^
      selectEligibility.hashCode ^
      deselectEligibility.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBykcCourse &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          courseName == other.courseName &&
          coursePosition == other.coursePosition &&
          courseTeacher == other.courseTeacher &&
          courseStartDate == other.courseStartDate &&
          courseEndDate == other.courseEndDate &&
          courseSelectStartDate == other.courseSelectStartDate &&
          courseSelectEndDate == other.courseSelectEndDate &&
          courseCancelEndDate == other.courseCancelEndDate &&
          courseMaxCount == other.courseMaxCount &&
          courseCurrentCount == other.courseCurrentCount &&
          status == other.status &&
          selected == other.selected &&
          selectEligibility == other.selectEligibility &&
          deselectEligibility == other.deselectEligibility;
}

enum BridgeBykcCourseCategory { boya, unknown }

class BridgeBykcCoursePage {
  final List<BridgeBykcCourse> content;
  final int totalElements;
  final int totalPages;
  final int size;
  final int number;

  const BridgeBykcCoursePage({
    required this.content,
    required this.totalElements,
    required this.totalPages,
    required this.size,
    required this.number,
  });

  @override
  int get hashCode =>
      content.hashCode ^
      totalElements.hashCode ^
      totalPages.hashCode ^
      size.hashCode ^
      number.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBykcCoursePage &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          totalElements == other.totalElements &&
          totalPages == other.totalPages &&
          size == other.size &&
          number == other.number;
}

enum BridgeBykcCourseStatus {
  expired,
  selected,
  preview,
  ended,
  full,
  available,
}

enum BridgeBykcCourseSubCategory {
  moral,
  aesthetic,
  labor,
  safetyHealth,
  other,
  unknown,
}

class BridgeBykcSignConfig {
  final String? signStartDate;
  final String? signEndDate;
  final String? signOutStartDate;
  final String? signOutEndDate;
  final List<BridgeBykcSignPoint> signPoints;

  const BridgeBykcSignConfig({
    this.signStartDate,
    this.signEndDate,
    this.signOutStartDate,
    this.signOutEndDate,
    required this.signPoints,
  });

  @override
  int get hashCode =>
      signStartDate.hashCode ^
      signEndDate.hashCode ^
      signOutStartDate.hashCode ^
      signOutEndDate.hashCode ^
      signPoints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBykcSignConfig &&
          runtimeType == other.runtimeType &&
          signStartDate == other.signStartDate &&
          signEndDate == other.signEndDate &&
          signOutStartDate == other.signOutStartDate &&
          signOutEndDate == other.signOutEndDate &&
          signPoints == other.signPoints;
}

class BridgeBykcSignPoint {
  final double lat;
  final double lng;
  final double radius;

  const BridgeBykcSignPoint({
    required this.lat,
    required this.lng,
    required this.radius,
  });

  @override
  int get hashCode => lat.hashCode ^ lng.hashCode ^ radius.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBykcSignPoint &&
          runtimeType == other.runtimeType &&
          lat == other.lat &&
          lng == other.lng &&
          radius == other.radius;
}

class BridgeBykcStatistic {
  final String? categoryName;
  final String? subCategoryName;
  final int? requiredCount;
  final int? passedCount;
  final bool? qualified;

  const BridgeBykcStatistic({
    this.categoryName,
    this.subCategoryName,
    this.requiredCount,
    this.passedCount,
    this.qualified,
  });

  @override
  int get hashCode =>
      categoryName.hashCode ^
      subCategoryName.hashCode ^
      requiredCount.hashCode ^
      passedCount.hashCode ^
      qualified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBykcStatistic &&
          runtimeType == other.runtimeType &&
          categoryName == other.categoryName &&
          subCategoryName == other.subCategoryName &&
          requiredCount == other.requiredCount &&
          passedCount == other.passedCount &&
          qualified == other.qualified;
}

class BridgeBykcStatistics {
  final int? totalValidCount;
  final List<BridgeBykcStatistic> categories;

  const BridgeBykcStatistics({this.totalValidCount, required this.categories});

  @override
  int get hashCode => totalValidCount.hashCode ^ categories.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBykcStatistics &&
          runtimeType == other.runtimeType &&
          totalValidCount == other.totalValidCount &&
          categories == other.categories;
}

class BridgeBykcUserProfile {
  final PlatformInt64 id;
  final String? employeeId;
  final String? realName;
  final String? studentNo;
  final String? collegeName;

  const BridgeBykcUserProfile({
    required this.id,
    this.employeeId,
    this.realName,
    this.studentNo,
    this.collegeName,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      employeeId.hashCode ^
      realName.hashCode ^
      studentNo.hashCode ^
      collegeName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBykcUserProfile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          employeeId == other.employeeId &&
          realName == other.realName &&
          studentNo == other.studentNo &&
          collegeName == other.collegeName;
}

/// 调用方固定路线的场馆订单详情结果；不表示 Core 重新执行了 Auto 探测。
class BridgeCallerPinnedCgyyOrder {
  final BridgeCgyyOrder data;
  final BridgeConnectionMode pinnedRoute;

  const BridgeCallerPinnedCgyyOrder({
    required this.data,
    required this.pinnedRoute,
  });

  @override
  int get hashCode => data.hashCode ^ pinnedRoute.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCallerPinnedCgyyOrder &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          pinnedRoute == other.pinnedRoute;
}

/// 调用方固定路线的场馆订单列表结果；不表示 Core 重新执行了 Auto 探测。
class BridgeCallerPinnedCgyyOrders {
  final BridgeCgyyOrdersPage data;
  final BridgeConnectionMode pinnedRoute;

  const BridgeCallerPinnedCgyyOrders({
    required this.data,
    required this.pinnedRoute,
  });

  @override
  int get hashCode => data.hashCode ^ pinnedRoute.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCallerPinnedCgyyOrders &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          pinnedRoute == other.pinnedRoute;
}

/// 调用方固定路线的评教课程结果；不表示 Core 重新执行了 Auto 探测。
class BridgeCallerPinnedEvaluation {
  final BridgeEvaluationCoursesResponse data;
  final BridgeConnectionMode pinnedRoute;

  const BridgeCallerPinnedEvaluation({
    required this.data,
    required this.pinnedRoute,
  });

  @override
  int get hashCode => data.hashCode ^ pinnedRoute.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCallerPinnedEvaluation &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          pinnedRoute == other.pinnedRoute;
}

/// 调用方固定路线的阳光打卡概览；不表示 Core 重新执行了 Auto 探测。
class BridgeCallerPinnedYgdkOverview {
  final BridgeYgdkOverview data;
  final BridgeConnectionMode pinnedRoute;

  const BridgeCallerPinnedYgdkOverview({
    required this.data,
    required this.pinnedRoute,
  });

  @override
  int get hashCode => data.hashCode ^ pinnedRoute.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCallerPinnedYgdkOverview &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          pinnedRoute == other.pinnedRoute;
}

/// 调用方固定路线的阳光打卡记录页；不表示 Core 重新执行了 Auto 探测。
class BridgeCallerPinnedYgdkRecords {
  final BridgeYgdkRecordsPage data;
  final BridgeConnectionMode pinnedRoute;

  const BridgeCallerPinnedYgdkRecords({
    required this.data,
    required this.pinnedRoute,
  });

  @override
  int get hashCode => data.hashCode ^ pinnedRoute.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCallerPinnedYgdkRecords &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          pinnedRoute == other.pinnedRoute;
}

class BridgeCgyyCancelOrderTarget {
  final int orderId;

  const BridgeCgyyCancelOrderTarget({required this.orderId});

  @override
  int get hashCode => orderId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCgyyCancelOrderTarget &&
          runtimeType == other.runtimeType &&
          orderId == other.orderId;
}

class BridgeCgyyDayInfo {
  final int venueSiteId;
  final String reservationDate;
  final List<String> availableDates;
  final List<BridgeCgyyTimeSlot> timeSlots;
  final List<BridgeCgyySpaceAvailability> spaces;
  final int? reservationTotalNum;

  const BridgeCgyyDayInfo({
    required this.venueSiteId,
    required this.reservationDate,
    required this.availableDates,
    required this.timeSlots,
    required this.spaces,
    this.reservationTotalNum,
  });

  @override
  int get hashCode =>
      venueSiteId.hashCode ^
      reservationDate.hashCode ^
      availableDates.hashCode ^
      timeSlots.hashCode ^
      spaces.hashCode ^
      reservationTotalNum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCgyyDayInfo &&
          runtimeType == other.runtimeType &&
          venueSiteId == other.venueSiteId &&
          reservationDate == other.reservationDate &&
          availableDates == other.availableDates &&
          timeSlots == other.timeSlots &&
          spaces == other.spaces &&
          reservationTotalNum == other.reservationTotalNum;
}

class BridgeCgyyLockCode {
  final bool available;

  const BridgeCgyyLockCode({required this.available});

  @override
  int get hashCode => available.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCgyyLockCode &&
          runtimeType == other.runtimeType &&
          available == other.available;
}

class BridgeCgyyOrder {
  final int id;
  final int? venueSiteId;
  final String? reservationDate;
  final String? reservationDateDetail;
  final String? venueSpaceName;
  final String? campusName;
  final String? venueName;
  final String? siteName;
  final String? reservationStartDate;
  final String? reservationEndDate;
  final int? orderStatus;
  final int? checkStatus;
  final String? theme;
  final String? purposeTypeName;
  final int? joinerNum;
  final BridgeActionEligibility cancelEligibility;
  final BridgeCgyyCancelOrderTarget? cancelTarget;
  final BridgeCgyyCancelOrderTarget? cancelledTarget;

  const BridgeCgyyOrder({
    required this.id,
    this.venueSiteId,
    this.reservationDate,
    this.reservationDateDetail,
    this.venueSpaceName,
    this.campusName,
    this.venueName,
    this.siteName,
    this.reservationStartDate,
    this.reservationEndDate,
    this.orderStatus,
    this.checkStatus,
    this.theme,
    this.purposeTypeName,
    this.joinerNum,
    required this.cancelEligibility,
    this.cancelTarget,
    this.cancelledTarget,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      venueSiteId.hashCode ^
      reservationDate.hashCode ^
      reservationDateDetail.hashCode ^
      venueSpaceName.hashCode ^
      campusName.hashCode ^
      venueName.hashCode ^
      siteName.hashCode ^
      reservationStartDate.hashCode ^
      reservationEndDate.hashCode ^
      orderStatus.hashCode ^
      checkStatus.hashCode ^
      theme.hashCode ^
      purposeTypeName.hashCode ^
      joinerNum.hashCode ^
      cancelEligibility.hashCode ^
      cancelTarget.hashCode ^
      cancelledTarget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCgyyOrder &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          venueSiteId == other.venueSiteId &&
          reservationDate == other.reservationDate &&
          reservationDateDetail == other.reservationDateDetail &&
          venueSpaceName == other.venueSpaceName &&
          campusName == other.campusName &&
          venueName == other.venueName &&
          siteName == other.siteName &&
          reservationStartDate == other.reservationStartDate &&
          reservationEndDate == other.reservationEndDate &&
          orderStatus == other.orderStatus &&
          checkStatus == other.checkStatus &&
          theme == other.theme &&
          purposeTypeName == other.purposeTypeName &&
          joinerNum == other.joinerNum &&
          cancelEligibility == other.cancelEligibility &&
          cancelTarget == other.cancelTarget &&
          cancelledTarget == other.cancelledTarget;
}

class BridgeCgyyOrdersPage {
  final List<BridgeCgyyOrder> content;
  final int totalElements;
  final int totalPages;
  final int size;
  final int number;

  const BridgeCgyyOrdersPage({
    required this.content,
    required this.totalElements,
    required this.totalPages,
    required this.size,
    required this.number,
  });

  @override
  int get hashCode =>
      content.hashCode ^
      totalElements.hashCode ^
      totalPages.hashCode ^
      size.hashCode ^
      number.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCgyyOrdersPage &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          totalElements == other.totalElements &&
          totalPages == other.totalPages &&
          size == other.size &&
          number == other.number;
}

enum BridgeCgyyPurposeSource { upstream, staticFallback }

class BridgeCgyyPurposeType {
  final int key;
  final String name;

  const BridgeCgyyPurposeType({required this.key, required this.name});

  @override
  int get hashCode => key.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCgyyPurposeType &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          name == other.name;
}

class BridgeCgyyPurposeTypes {
  final List<BridgeCgyyPurposeType> items;
  final BridgeCgyyPurposeSource source;

  const BridgeCgyyPurposeTypes({required this.items, required this.source});

  @override
  int get hashCode => items.hashCode ^ source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCgyyPurposeTypes &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          source == other.source;
}

class BridgeCgyyReservationTarget {
  final int venueSiteId;
  final String reservationDate;
  final int spaceId;
  final int timeId;
  final int? venueSpaceGroupId;
  final int timeOrdinal;

  const BridgeCgyyReservationTarget({
    required this.venueSiteId,
    required this.reservationDate,
    required this.spaceId,
    required this.timeId,
    this.venueSpaceGroupId,
    required this.timeOrdinal,
  });

  @override
  int get hashCode =>
      venueSiteId.hashCode ^
      reservationDate.hashCode ^
      spaceId.hashCode ^
      timeId.hashCode ^
      venueSpaceGroupId.hashCode ^
      timeOrdinal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCgyyReservationTarget &&
          runtimeType == other.runtimeType &&
          venueSiteId == other.venueSiteId &&
          reservationDate == other.reservationDate &&
          spaceId == other.spaceId &&
          timeId == other.timeId &&
          venueSpaceGroupId == other.venueSpaceGroupId &&
          timeOrdinal == other.timeOrdinal;
}

class BridgeCgyySlotStatus {
  final int timeId;
  final int? reservationStatus;
  final BridgeActionEligibility reservationEligibility;
  final BridgeCgyyReservationTarget? reservationTarget;
  final String? startDate;
  final String? endDate;

  const BridgeCgyySlotStatus({
    required this.timeId,
    this.reservationStatus,
    required this.reservationEligibility,
    this.reservationTarget,
    this.startDate,
    this.endDate,
  });

  @override
  int get hashCode =>
      timeId.hashCode ^
      reservationStatus.hashCode ^
      reservationEligibility.hashCode ^
      reservationTarget.hashCode ^
      startDate.hashCode ^
      endDate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCgyySlotStatus &&
          runtimeType == other.runtimeType &&
          timeId == other.timeId &&
          reservationStatus == other.reservationStatus &&
          reservationEligibility == other.reservationEligibility &&
          reservationTarget == other.reservationTarget &&
          startDate == other.startDate &&
          endDate == other.endDate;
}

class BridgeCgyySpaceAvailability {
  final int spaceId;
  final String spaceName;
  final int venueSiteId;
  final int? venueSpaceGroupId;
  final List<BridgeCgyySlotStatus> slots;

  const BridgeCgyySpaceAvailability({
    required this.spaceId,
    required this.spaceName,
    required this.venueSiteId,
    this.venueSpaceGroupId,
    required this.slots,
  });

  @override
  int get hashCode =>
      spaceId.hashCode ^
      spaceName.hashCode ^
      venueSiteId.hashCode ^
      venueSpaceGroupId.hashCode ^
      slots.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCgyySpaceAvailability &&
          runtimeType == other.runtimeType &&
          spaceId == other.spaceId &&
          spaceName == other.spaceName &&
          venueSiteId == other.venueSiteId &&
          venueSpaceGroupId == other.venueSpaceGroupId &&
          slots == other.slots;
}

class BridgeCgyyTimeSlot {
  final int id;
  final String beginTime;
  final String endTime;
  final String label;

  const BridgeCgyyTimeSlot({
    required this.id,
    required this.beginTime,
    required this.endTime,
    required this.label,
  });

  @override
  int get hashCode =>
      id.hashCode ^ beginTime.hashCode ^ endTime.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCgyyTimeSlot &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          beginTime == other.beginTime &&
          endTime == other.endTime &&
          label == other.label;
}

class BridgeCgyyVenueSite {
  final int id;
  final String siteName;
  final String venueName;
  final String campusName;
  final int? seatCount;
  final int? reservationSpaceCount;
  final String? siteTelephone;
  final String? openStartDate;
  final String? openEndDate;

  const BridgeCgyyVenueSite({
    required this.id,
    required this.siteName,
    required this.venueName,
    required this.campusName,
    this.seatCount,
    this.reservationSpaceCount,
    this.siteTelephone,
    this.openStartDate,
    this.openEndDate,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      siteName.hashCode ^
      venueName.hashCode ^
      campusName.hashCode ^
      seatCount.hashCode ^
      reservationSpaceCount.hashCode ^
      siteTelephone.hashCode ^
      openStartDate.hashCode ^
      openEndDate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCgyyVenueSite &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          siteName == other.siteName &&
          venueName == other.venueName &&
          campusName == other.campusName &&
          seatCount == other.seatCount &&
          reservationSpaceCount == other.reservationSpaceCount &&
          siteTelephone == other.siteTelephone &&
          openStartDate == other.openStartDate &&
          openEndDate == other.openEndDate;
}

class BridgeClassroomFloor {
  final String name;
  final List<BridgeClassroomInfo> rooms;

  const BridgeClassroomFloor({required this.name, required this.rooms});

  @override
  int get hashCode => name.hashCode ^ rooms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeClassroomFloor &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          rooms == other.rooms;
}

class BridgeClassroomInfo {
  final String id;
  final String floorId;
  final String name;
  final String availableSections;

  const BridgeClassroomInfo({
    required this.id,
    required this.floorId,
    required this.name,
    required this.availableSections,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      floorId.hashCode ^
      name.hashCode ^
      availableSections.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeClassroomInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          floorId == other.floorId &&
          name == other.name &&
          availableSections == other.availableSections;
}

class BridgeClassroomQuery {
  final int code;
  final String message;
  final List<BridgeClassroomFloor> floors;

  const BridgeClassroomQuery({
    required this.code,
    required this.message,
    required this.floors,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode ^ floors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeClassroomQuery &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          floors == other.floors;
}

class BridgeCourseClass {
  final String courseCode;
  final String courseName;
  final String? courseSerialNo;
  final String? credit;
  final String? beginTime;
  final String? endTime;
  final int? beginSection;
  final int? endSection;
  final String? placeName;
  final String? weeksAndTeachers;
  final String? teachingTarget;
  final String? color;
  final int? dayOfWeek;

  const BridgeCourseClass({
    required this.courseCode,
    required this.courseName,
    this.courseSerialNo,
    this.credit,
    this.beginTime,
    this.endTime,
    this.beginSection,
    this.endSection,
    this.placeName,
    this.weeksAndTeachers,
    this.teachingTarget,
    this.color,
    this.dayOfWeek,
  });

  @override
  int get hashCode =>
      courseCode.hashCode ^
      courseName.hashCode ^
      courseSerialNo.hashCode ^
      credit.hashCode ^
      beginTime.hashCode ^
      endTime.hashCode ^
      beginSection.hashCode ^
      endSection.hashCode ^
      placeName.hashCode ^
      weeksAndTeachers.hashCode ^
      teachingTarget.hashCode ^
      color.hashCode ^
      dayOfWeek.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCourseClass &&
          runtimeType == other.runtimeType &&
          courseCode == other.courseCode &&
          courseName == other.courseName &&
          courseSerialNo == other.courseSerialNo &&
          credit == other.credit &&
          beginTime == other.beginTime &&
          endTime == other.endTime &&
          beginSection == other.beginSection &&
          endSection == other.endSection &&
          placeName == other.placeName &&
          weeksAndTeachers == other.weeksAndTeachers &&
          teachingTarget == other.teachingTarget &&
          color == other.color &&
          dayOfWeek == other.dayOfWeek;
}

class BridgeEvaluationCourse {
  final String id;
  final String kcmc;
  final String bpmc;
  final bool isEvaluated;
  final BridgeActionEligibility submitEligibility;
  final BridgeEvaluationSubmitTarget? submitTarget;

  const BridgeEvaluationCourse({
    required this.id,
    required this.kcmc,
    required this.bpmc,
    required this.isEvaluated,
    required this.submitEligibility,
    this.submitTarget,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kcmc.hashCode ^
      bpmc.hashCode ^
      isEvaluated.hashCode ^
      submitEligibility.hashCode ^
      submitTarget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEvaluationCourse &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kcmc == other.kcmc &&
          bpmc == other.bpmc &&
          isEvaluated == other.isEvaluated &&
          submitEligibility == other.submitEligibility &&
          submitTarget == other.submitTarget;
}

class BridgeEvaluationCoursesResponse {
  final List<BridgeEvaluationCourse> courses;
  final BridgeEvaluationProgress progress;

  const BridgeEvaluationCoursesResponse({
    required this.courses,
    required this.progress,
  });

  @override
  int get hashCode => courses.hashCode ^ progress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEvaluationCoursesResponse &&
          runtimeType == other.runtimeType &&
          courses == other.courses &&
          progress == other.progress;
}

class BridgeEvaluationProgress {
  final int totalCourses;
  final int evaluatedCourses;
  final int pendingCourses;

  const BridgeEvaluationProgress({
    required this.totalCourses,
    required this.evaluatedCourses,
    required this.pendingCourses,
  });

  @override
  int get hashCode =>
      totalCourses.hashCode ^
      evaluatedCourses.hashCode ^
      pendingCourses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEvaluationProgress &&
          runtimeType == other.runtimeType &&
          totalCourses == other.totalCourses &&
          evaluatedCourses == other.evaluatedCourses &&
          pendingCourses == other.pendingCourses;
}

class BridgeEvaluationSubmitTarget {
  final String rwid;
  final String wjid;
  final String kcdm;
  final String? bpdm;

  const BridgeEvaluationSubmitTarget({
    required this.rwid,
    required this.wjid,
    required this.kcdm,
    this.bpdm,
  });

  @override
  int get hashCode =>
      rwid.hashCode ^ wjid.hashCode ^ kcdm.hashCode ^ bpdm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeEvaluationSubmitTarget &&
          runtimeType == other.runtimeType &&
          rwid == other.rwid &&
          wjid == other.wjid &&
          kcdm == other.kcdm &&
          bpdm == other.bpdm;
}

class BridgeExam {
  final String courseName;
  final String? courseNo;
  final String? examTimeDescription;
  final String? examDate;
  final String? startTime;
  final String? endTime;
  final String? examPlace;
  final String? examSeatNo;
  final int? week;
  final int? examStatus;
  final String? examType;
  final String? taskId;

  const BridgeExam({
    required this.courseName,
    this.courseNo,
    this.examTimeDescription,
    this.examDate,
    this.startTime,
    this.endTime,
    this.examPlace,
    this.examSeatNo,
    this.week,
    this.examStatus,
    this.examType,
    this.taskId,
  });

  @override
  int get hashCode =>
      courseName.hashCode ^
      courseNo.hashCode ^
      examTimeDescription.hashCode ^
      examDate.hashCode ^
      startTime.hashCode ^
      endTime.hashCode ^
      examPlace.hashCode ^
      examSeatNo.hashCode ^
      week.hashCode ^
      examStatus.hashCode ^
      examType.hashCode ^
      taskId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeExam &&
          runtimeType == other.runtimeType &&
          courseName == other.courseName &&
          courseNo == other.courseNo &&
          examTimeDescription == other.examTimeDescription &&
          examDate == other.examDate &&
          startTime == other.startTime &&
          endTime == other.endTime &&
          examPlace == other.examPlace &&
          examSeatNo == other.examSeatNo &&
          week == other.week &&
          examStatus == other.examStatus &&
          examType == other.examType &&
          taskId == other.taskId;
}

class BridgeExamArrangement {
  final List<BridgeExam> arranged;
  final List<BridgeExam> notArranged;

  const BridgeExamArrangement({
    required this.arranged,
    required this.notArranged,
  });

  @override
  int get hashCode => arranged.hashCode ^ notArranged.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeExamArrangement &&
          runtimeType == other.runtimeType &&
          arranged == other.arranged &&
          notArranged == other.notArranged;
}

class BridgeGrade {
  final bool graduate;
  final String? termName;
  final double? averageScore;
  final String? courseName;
  final String? courseCode;
  final double? credit;
  final String? score;
  final String? gradePoint;
  final String? courseType;
  final String? scoreType;
  final String? termCode;

  const BridgeGrade({
    required this.graduate,
    this.termName,
    this.averageScore,
    this.courseName,
    this.courseCode,
    this.credit,
    this.score,
    this.gradePoint,
    this.courseType,
    this.scoreType,
    this.termCode,
  });

  @override
  int get hashCode =>
      graduate.hashCode ^
      termName.hashCode ^
      averageScore.hashCode ^
      courseName.hashCode ^
      courseCode.hashCode ^
      credit.hashCode ^
      score.hashCode ^
      gradePoint.hashCode ^
      courseType.hashCode ^
      scoreType.hashCode ^
      termCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeGrade &&
          runtimeType == other.runtimeType &&
          graduate == other.graduate &&
          termName == other.termName &&
          averageScore == other.averageScore &&
          courseName == other.courseName &&
          courseCode == other.courseCode &&
          credit == other.credit &&
          score == other.score &&
          gradePoint == other.gradePoint &&
          courseType == other.courseType &&
          scoreType == other.scoreType &&
          termCode == other.termCode;
}

class BridgeGradeData {
  final String termCode;
  final List<BridgeGrade> grades;

  const BridgeGradeData({required this.termCode, required this.grades});

  @override
  int get hashCode => termCode.hashCode ^ grades.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeGradeData &&
          runtimeType == other.runtimeType &&
          termCode == other.termCode &&
          grades == other.grades;
}

class BridgeGradeOverview {
  final bool graduate;
  final List<BridgeGrade> grades;
  final BridgeGradeStatistics? statistics;
  final List<BridgeGradeTermStatistics> terms;

  const BridgeGradeOverview({
    required this.graduate,
    required this.grades,
    this.statistics,
    required this.terms,
  });

  @override
  int get hashCode =>
      graduate.hashCode ^
      grades.hashCode ^
      statistics.hashCode ^
      terms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeGradeOverview &&
          runtimeType == other.runtimeType &&
          graduate == other.graduate &&
          grades == other.grades &&
          statistics == other.statistics &&
          terms == other.terms;
}

class BridgeGradeStatistics {
  final double? gpa;
  final double? averageScore;
  final double gpaCredits;
  final double averageCredits;

  const BridgeGradeStatistics({
    this.gpa,
    this.averageScore,
    required this.gpaCredits,
    required this.averageCredits,
  });

  @override
  int get hashCode =>
      gpa.hashCode ^
      averageScore.hashCode ^
      gpaCredits.hashCode ^
      averageCredits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeGradeStatistics &&
          runtimeType == other.runtimeType &&
          gpa == other.gpa &&
          averageScore == other.averageScore &&
          gpaCredits == other.gpaCredits &&
          averageCredits == other.averageCredits;
}

class BridgeGradeTermStatistics {
  final String termCode;
  final String termName;
  final BridgeGradeStatistics statistics;

  const BridgeGradeTermStatistics({
    required this.termCode,
    required this.termName,
    required this.statistics,
  });

  @override
  int get hashCode =>
      termCode.hashCode ^ termName.hashCode ^ statistics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeGradeTermStatistics &&
          runtimeType == other.runtimeType &&
          termCode == other.termCode &&
          termName == other.termName &&
          statistics == other.statistics;
}

class BridgeJudgeAssignmentDetail {
  final String courseId;
  final String courseName;
  final String assignmentId;
  final String title;
  final String? startTime;
  final String? dueTime;
  final String? maxScore;
  final String? myScore;
  final int totalProblems;
  final int submittedCount;
  final BridgeJudgeSubmissionStatus submissionStatus;
  final String submissionStatusText;
  final List<BridgeJudgeProblem> problems;
  final String? contentPlainText;

  const BridgeJudgeAssignmentDetail({
    required this.courseId,
    required this.courseName,
    required this.assignmentId,
    required this.title,
    this.startTime,
    this.dueTime,
    this.maxScore,
    this.myScore,
    required this.totalProblems,
    required this.submittedCount,
    required this.submissionStatus,
    required this.submissionStatusText,
    required this.problems,
    this.contentPlainText,
  });

  @override
  int get hashCode =>
      courseId.hashCode ^
      courseName.hashCode ^
      assignmentId.hashCode ^
      title.hashCode ^
      startTime.hashCode ^
      dueTime.hashCode ^
      maxScore.hashCode ^
      myScore.hashCode ^
      totalProblems.hashCode ^
      submittedCount.hashCode ^
      submissionStatus.hashCode ^
      submissionStatusText.hashCode ^
      problems.hashCode ^
      contentPlainText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeJudgeAssignmentDetail &&
          runtimeType == other.runtimeType &&
          courseId == other.courseId &&
          courseName == other.courseName &&
          assignmentId == other.assignmentId &&
          title == other.title &&
          startTime == other.startTime &&
          dueTime == other.dueTime &&
          maxScore == other.maxScore &&
          myScore == other.myScore &&
          totalProblems == other.totalProblems &&
          submittedCount == other.submittedCount &&
          submissionStatus == other.submissionStatus &&
          submissionStatusText == other.submissionStatusText &&
          problems == other.problems &&
          contentPlainText == other.contentPlainText;
}

class BridgeJudgeAssignmentKey {
  final String courseId;
  final String assignmentId;

  const BridgeJudgeAssignmentKey({
    required this.courseId,
    required this.assignmentId,
  });

  @override
  int get hashCode => courseId.hashCode ^ assignmentId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeJudgeAssignmentKey &&
          runtimeType == other.runtimeType &&
          courseId == other.courseId &&
          assignmentId == other.assignmentId;
}

class BridgeJudgeAssignmentSummary {
  final String courseId;
  final String courseName;
  final String assignmentId;
  final String title;
  final String? startTime;
  final String? dueTime;
  final String? maxScore;
  final String? myScore;
  final int totalProblems;
  final int submittedCount;
  final BridgeJudgeSubmissionStatus submissionStatus;
  final String submissionStatusText;

  const BridgeJudgeAssignmentSummary({
    required this.courseId,
    required this.courseName,
    required this.assignmentId,
    required this.title,
    this.startTime,
    this.dueTime,
    this.maxScore,
    this.myScore,
    required this.totalProblems,
    required this.submittedCount,
    required this.submissionStatus,
    required this.submissionStatusText,
  });

  @override
  int get hashCode =>
      courseId.hashCode ^
      courseName.hashCode ^
      assignmentId.hashCode ^
      title.hashCode ^
      startTime.hashCode ^
      dueTime.hashCode ^
      maxScore.hashCode ^
      myScore.hashCode ^
      totalProblems.hashCode ^
      submittedCount.hashCode ^
      submissionStatus.hashCode ^
      submissionStatusText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeJudgeAssignmentSummary &&
          runtimeType == other.runtimeType &&
          courseId == other.courseId &&
          courseName == other.courseName &&
          assignmentId == other.assignmentId &&
          title == other.title &&
          startTime == other.startTime &&
          dueTime == other.dueTime &&
          maxScore == other.maxScore &&
          myScore == other.myScore &&
          totalProblems == other.totalProblems &&
          submittedCount == other.submittedCount &&
          submissionStatus == other.submissionStatus &&
          submissionStatusText == other.submissionStatusText;
}

class BridgeJudgeProblem {
  final String name;
  final String? score;
  final String? maxScore;
  final BridgeJudgeSubmissionStatus status;
  final String statusText;

  const BridgeJudgeProblem({
    required this.name,
    this.score,
    this.maxScore,
    required this.status,
    required this.statusText,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      score.hashCode ^
      maxScore.hashCode ^
      status.hashCode ^
      statusText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeJudgeProblem &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          score == other.score &&
          maxScore == other.maxScore &&
          status == other.status &&
          statusText == other.statusText;
}

enum BridgeJudgeSubmissionStatus { submitted, partial, unsubmitted, unknown }

class BridgeLibBookArea {
  final String id;
  final String name;
  final String areaName;
  final String premisesId;
  final String storeyId;
  final int freeNum;
  final int totalNum;

  const BridgeLibBookArea({
    required this.id,
    required this.name,
    required this.areaName,
    required this.premisesId,
    required this.storeyId,
    required this.freeNum,
    required this.totalNum,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      areaName.hashCode ^
      premisesId.hashCode ^
      storeyId.hashCode ^
      freeNum.hashCode ^
      totalNum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLibBookArea &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          areaName == other.areaName &&
          premisesId == other.premisesId &&
          storeyId == other.storeyId &&
          freeNum == other.freeNum &&
          totalNum == other.totalNum;
}

class BridgeLibBookAreaDetail {
  final String id;
  final String name;
  final List<String> availableDates;
  final List<BridgeLibBookTimeSlot> timeSlots;

  const BridgeLibBookAreaDetail({
    required this.id,
    required this.name,
    required this.availableDates,
    required this.timeSlots,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      availableDates.hashCode ^
      timeSlots.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLibBookAreaDetail &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          availableDates == other.availableDates &&
          timeSlots == other.timeSlots;
}

class BridgeLibBookBooking {
  final String id;
  final String nameMerge;
  final String areaName;
  final String seatNo;
  final String day;
  final String beginTime;
  final String endTime;
  final int? status;
  final String statusName;
  final BridgeActionEligibility cancelEligibility;
  final String? cancelTarget;

  const BridgeLibBookBooking({
    required this.id,
    required this.nameMerge,
    required this.areaName,
    required this.seatNo,
    required this.day,
    required this.beginTime,
    required this.endTime,
    this.status,
    required this.statusName,
    required this.cancelEligibility,
    this.cancelTarget,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      nameMerge.hashCode ^
      areaName.hashCode ^
      seatNo.hashCode ^
      day.hashCode ^
      beginTime.hashCode ^
      endTime.hashCode ^
      status.hashCode ^
      statusName.hashCode ^
      cancelEligibility.hashCode ^
      cancelTarget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLibBookBooking &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          nameMerge == other.nameMerge &&
          areaName == other.areaName &&
          seatNo == other.seatNo &&
          day == other.day &&
          beginTime == other.beginTime &&
          endTime == other.endTime &&
          status == other.status &&
          statusName == other.statusName &&
          cancelEligibility == other.cancelEligibility &&
          cancelTarget == other.cancelTarget;
}

class BridgeLibBookBookingsPage {
  final List<BridgeLibBookBooking> bookings;
  final int page;
  final int limit;
  final int total;

  const BridgeLibBookBookingsPage({
    required this.bookings,
    required this.page,
    required this.limit,
    required this.total,
  });

  @override
  int get hashCode =>
      bookings.hashCode ^ page.hashCode ^ limit.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLibBookBookingsPage &&
          runtimeType == other.runtimeType &&
          bookings == other.bookings &&
          page == other.page &&
          limit == other.limit &&
          total == other.total;
}

class BridgeLibBookLibrary {
  final String id;
  final String name;
  final int freeNum;
  final int totalNum;
  final List<BridgeLibBookStorey> storeys;

  const BridgeLibBookLibrary({
    required this.id,
    required this.name,
    required this.freeNum,
    required this.totalNum,
    required this.storeys,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      freeNum.hashCode ^
      totalNum.hashCode ^
      storeys.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLibBookLibrary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          freeNum == other.freeNum &&
          totalNum == other.totalNum &&
          storeys == other.storeys;
}

class BridgeLibBookSeat {
  final String id;
  final String name;
  final String no;
  final int? status;
  final String statusName;
  final BridgeActionEligibility reserveEligibility;
  final String? reserveTarget;

  const BridgeLibBookSeat({
    required this.id,
    required this.name,
    required this.no,
    this.status,
    required this.statusName,
    required this.reserveEligibility,
    this.reserveTarget,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      no.hashCode ^
      status.hashCode ^
      statusName.hashCode ^
      reserveEligibility.hashCode ^
      reserveTarget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLibBookSeat &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          no == other.no &&
          status == other.status &&
          statusName == other.statusName &&
          reserveEligibility == other.reserveEligibility &&
          reserveTarget == other.reserveTarget;
}

class BridgeLibBookStorey {
  final String id;
  final String name;
  final int freeNum;
  final int totalNum;

  const BridgeLibBookStorey({
    required this.id,
    required this.name,
    required this.freeNum,
    required this.totalNum,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ freeNum.hashCode ^ totalNum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLibBookStorey &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          freeNum == other.freeNum &&
          totalNum == other.totalNum;
}

class BridgeLibBookTimeSlot {
  final String id;
  final String start;
  final String end;
  final String label;

  const BridgeLibBookTimeSlot({
    required this.id,
    required this.start,
    required this.end,
    required this.label,
  });

  @override
  int get hashCode =>
      id.hashCode ^ start.hashCode ^ end.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLibBookTimeSlot &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          start == other.start &&
          end == other.end &&
          label == other.label;
}

class BridgeRoutedBykcChosenCourses {
  final List<BridgeBykcChosenCourse> data;
  final BridgeRouteDecision route;

  const BridgeRoutedBykcChosenCourses({
    required this.data,
    required this.route,
  });

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedBykcChosenCourses &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedBykcCourse {
  final BridgeBykcCourse data;
  final BridgeRouteDecision route;

  const BridgeRoutedBykcCourse({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedBykcCourse &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedBykcCourses {
  final BridgeBykcCoursePage data;
  final BridgeRouteDecision route;

  const BridgeRoutedBykcCourses({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedBykcCourses &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedBykcProfile {
  final BridgeBykcUserProfile data;
  final BridgeRouteDecision route;

  const BridgeRoutedBykcProfile({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedBykcProfile &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedBykcStatistics {
  final BridgeBykcStatistics data;
  final BridgeRouteDecision route;

  const BridgeRoutedBykcStatistics({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedBykcStatistics &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedCgyyDayInfo {
  final BridgeCgyyDayInfo data;
  final BridgeRouteDecision route;

  const BridgeRoutedCgyyDayInfo({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedCgyyDayInfo &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedCgyyLockCode {
  final BridgeCgyyLockCode data;
  final BridgeRouteDecision route;

  const BridgeRoutedCgyyLockCode({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedCgyyLockCode &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedCgyyOrder {
  final BridgeCgyyOrder data;
  final BridgeRouteDecision route;

  const BridgeRoutedCgyyOrder({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedCgyyOrder &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedCgyyOrders {
  final BridgeCgyyOrdersPage data;
  final BridgeRouteDecision route;

  const BridgeRoutedCgyyOrders({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedCgyyOrders &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedCgyyPurposeTypes {
  final BridgeCgyyPurposeTypes data;
  final BridgeRouteDecision route;

  const BridgeRoutedCgyyPurposeTypes({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedCgyyPurposeTypes &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedCgyySites {
  final List<BridgeCgyyVenueSite> data;
  final BridgeRouteDecision route;

  const BridgeRoutedCgyySites({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedCgyySites &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedClassroomQuery {
  final BridgeClassroomQuery data;
  final BridgeRouteDecision route;

  const BridgeRoutedClassroomQuery({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedClassroomQuery &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedEvaluation {
  final BridgeEvaluationCoursesResponse data;
  final BridgeRouteDecision route;

  const BridgeRoutedEvaluation({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedEvaluation &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedExamArrangement {
  final BridgeExamArrangement data;
  final BridgeRouteDecision route;

  const BridgeRoutedExamArrangement({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedExamArrangement &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedGradeOverview {
  final BridgeGradeOverview data;
  final BridgeRouteDecision route;

  const BridgeRoutedGradeOverview({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedGradeOverview &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedGrades {
  final BridgeGradeData data;
  final BridgeRouteDecision route;

  const BridgeRoutedGrades({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedGrades &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedJudgeAssignmentDetail {
  final BridgeJudgeAssignmentDetail data;
  final BridgeRouteDecision route;

  const BridgeRoutedJudgeAssignmentDetail({
    required this.data,
    required this.route,
  });

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedJudgeAssignmentDetail &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedJudgeAssignmentDetails {
  final List<BridgeJudgeAssignmentDetail> data;
  final BridgeRouteDecision route;

  const BridgeRoutedJudgeAssignmentDetails({
    required this.data,
    required this.route,
  });

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedJudgeAssignmentDetails &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedJudgeSummaries {
  final List<BridgeJudgeAssignmentSummary> data;
  final BridgeRouteDecision route;

  const BridgeRoutedJudgeSummaries({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedJudgeSummaries &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedLibBookAreaDetail {
  final BridgeLibBookAreaDetail data;
  final BridgeRouteDecision route;

  const BridgeRoutedLibBookAreaDetail({
    required this.data,
    required this.route,
  });

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedLibBookAreaDetail &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedLibBookAreas {
  final List<BridgeLibBookArea> data;
  final BridgeRouteDecision route;

  const BridgeRoutedLibBookAreas({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedLibBookAreas &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedLibBookBookings {
  final BridgeLibBookBookingsPage data;
  final BridgeRouteDecision route;

  const BridgeRoutedLibBookBookings({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedLibBookBookings &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedLibBookLibraries {
  final List<BridgeLibBookLibrary> data;
  final BridgeRouteDecision route;

  const BridgeRoutedLibBookLibraries({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedLibBookLibraries &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedLibBookSeats {
  final List<BridgeLibBookSeat> data;
  final BridgeRouteDecision route;

  const BridgeRoutedLibBookSeats({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedLibBookSeats &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedSigninClasses {
  final List<BridgeSigninClass> data;
  final BridgeRouteDecision route;

  const BridgeRoutedSigninClasses({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedSigninClasses &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedSpocAssignmentDetail {
  final BridgeSpocAssignmentDetail data;
  final BridgeRouteDecision route;

  const BridgeRoutedSpocAssignmentDetail({
    required this.data,
    required this.route,
  });

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedSpocAssignmentDetail &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedSpocAssignments {
  final BridgeSpocAssignments data;
  final BridgeRouteDecision route;

  const BridgeRoutedSpocAssignments({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedSpocAssignments &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedTerms {
  final List<BridgeTerm> data;
  final BridgeRouteDecision route;

  const BridgeRoutedTerms({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedTerms &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedTodayClasses {
  final List<BridgeTodayClass> data;
  final BridgeRouteDecision route;

  const BridgeRoutedTodayClasses({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedTodayClasses &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedWeeklySchedule {
  final BridgeWeeklySchedule data;
  final BridgeRouteDecision route;

  const BridgeRoutedWeeklySchedule({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedWeeklySchedule &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedWeeks {
  final List<BridgeWeek> data;
  final BridgeRouteDecision route;

  const BridgeRoutedWeeks({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedWeeks &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedYgdkOverview {
  final BridgeYgdkOverview data;
  final BridgeRouteDecision route;

  const BridgeRoutedYgdkOverview({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedYgdkOverview &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeRoutedYgdkRecords {
  final BridgeYgdkRecordsPage data;
  final BridgeRouteDecision route;

  const BridgeRoutedYgdkRecords({required this.data, required this.route});

  @override
  int get hashCode => data.hashCode ^ route.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRoutedYgdkRecords &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          route == other.route;
}

class BridgeSectionTime {
  final int section;
  final String startTime;
  final String endTime;

  const BridgeSectionTime({
    required this.section,
    required this.startTime,
    required this.endTime,
  });

  @override
  int get hashCode => section.hashCode ^ startTime.hashCode ^ endTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSectionTime &&
          runtimeType == other.runtimeType &&
          section == other.section &&
          startTime == other.startTime &&
          endTime == other.endTime;
}

class BridgeSigninClass {
  final String courseId;
  final String courseName;
  final String classBeginTime;
  final String classEndTime;
  final int? signStatus;
  final BridgeActionEligibility signinEligibility;
  final String? signinTarget;

  const BridgeSigninClass({
    required this.courseId,
    required this.courseName,
    required this.classBeginTime,
    required this.classEndTime,
    this.signStatus,
    required this.signinEligibility,
    this.signinTarget,
  });

  @override
  int get hashCode =>
      courseId.hashCode ^
      courseName.hashCode ^
      classBeginTime.hashCode ^
      classEndTime.hashCode ^
      signStatus.hashCode ^
      signinEligibility.hashCode ^
      signinTarget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSigninClass &&
          runtimeType == other.runtimeType &&
          courseId == other.courseId &&
          courseName == other.courseName &&
          classBeginTime == other.classBeginTime &&
          classEndTime == other.classEndTime &&
          signStatus == other.signStatus &&
          signinEligibility == other.signinEligibility &&
          signinTarget == other.signinTarget;
}

class BridgeSpocAssignmentDetail {
  final String assignmentId;
  final String courseId;
  final String courseName;
  final String? teacherName;
  final String title;
  final String? startTime;
  final String? dueTime;
  final String? score;
  final BridgeSpocSubmissionStatus submissionStatus;
  final String submissionStatusText;
  final String? contentPlainText;
  final String? submittedAt;

  const BridgeSpocAssignmentDetail({
    required this.assignmentId,
    required this.courseId,
    required this.courseName,
    this.teacherName,
    required this.title,
    this.startTime,
    this.dueTime,
    this.score,
    required this.submissionStatus,
    required this.submissionStatusText,
    this.contentPlainText,
    this.submittedAt,
  });

  @override
  int get hashCode =>
      assignmentId.hashCode ^
      courseId.hashCode ^
      courseName.hashCode ^
      teacherName.hashCode ^
      title.hashCode ^
      startTime.hashCode ^
      dueTime.hashCode ^
      score.hashCode ^
      submissionStatus.hashCode ^
      submissionStatusText.hashCode ^
      contentPlainText.hashCode ^
      submittedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSpocAssignmentDetail &&
          runtimeType == other.runtimeType &&
          assignmentId == other.assignmentId &&
          courseId == other.courseId &&
          courseName == other.courseName &&
          teacherName == other.teacherName &&
          title == other.title &&
          startTime == other.startTime &&
          dueTime == other.dueTime &&
          score == other.score &&
          submissionStatus == other.submissionStatus &&
          submissionStatusText == other.submissionStatusText &&
          contentPlainText == other.contentPlainText &&
          submittedAt == other.submittedAt;
}

class BridgeSpocAssignmentSummary {
  final String assignmentId;
  final String courseId;
  final String courseName;
  final String? teacherName;
  final String title;
  final String? startTime;
  final String? dueTime;
  final String? score;
  final BridgeSpocSubmissionStatus submissionStatus;
  final String submissionStatusText;

  const BridgeSpocAssignmentSummary({
    required this.assignmentId,
    required this.courseId,
    required this.courseName,
    this.teacherName,
    required this.title,
    this.startTime,
    this.dueTime,
    this.score,
    required this.submissionStatus,
    required this.submissionStatusText,
  });

  @override
  int get hashCode =>
      assignmentId.hashCode ^
      courseId.hashCode ^
      courseName.hashCode ^
      teacherName.hashCode ^
      title.hashCode ^
      startTime.hashCode ^
      dueTime.hashCode ^
      score.hashCode ^
      submissionStatus.hashCode ^
      submissionStatusText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSpocAssignmentSummary &&
          runtimeType == other.runtimeType &&
          assignmentId == other.assignmentId &&
          courseId == other.courseId &&
          courseName == other.courseName &&
          teacherName == other.teacherName &&
          title == other.title &&
          startTime == other.startTime &&
          dueTime == other.dueTime &&
          score == other.score &&
          submissionStatus == other.submissionStatus &&
          submissionStatusText == other.submissionStatusText;
}

class BridgeSpocAssignments {
  final String termCode;
  final String? termName;
  final List<BridgeSpocAssignmentSummary> assignments;

  const BridgeSpocAssignments({
    required this.termCode,
    this.termName,
    required this.assignments,
  });

  @override
  int get hashCode =>
      termCode.hashCode ^ termName.hashCode ^ assignments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSpocAssignments &&
          runtimeType == other.runtimeType &&
          termCode == other.termCode &&
          termName == other.termName &&
          assignments == other.assignments;
}

enum BridgeSpocSubmissionStatus { submitted, unsubmitted, unknown }

class BridgeTerm {
  final String itemCode;
  final String itemName;
  final bool selected;
  final int itemIndex;

  const BridgeTerm({
    required this.itemCode,
    required this.itemName,
    required this.selected,
    required this.itemIndex,
  });

  @override
  int get hashCode =>
      itemCode.hashCode ^
      itemName.hashCode ^
      selected.hashCode ^
      itemIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeTerm &&
          runtimeType == other.runtimeType &&
          itemCode == other.itemCode &&
          itemName == other.itemName &&
          selected == other.selected &&
          itemIndex == other.itemIndex;
}

class BridgeTodayClass {
  final String bizName;
  final String? place;
  final String? time;
  final String? shortName;

  const BridgeTodayClass({
    required this.bizName,
    this.place,
    this.time,
    this.shortName,
  });

  @override
  int get hashCode =>
      bizName.hashCode ^ place.hashCode ^ time.hashCode ^ shortName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeTodayClass &&
          runtimeType == other.runtimeType &&
          bizName == other.bizName &&
          place == other.place &&
          time == other.time &&
          shortName == other.shortName;
}

class BridgeWeek {
  final String startDate;
  final String endDate;
  final String term;
  final bool curWeek;
  final int serialNumber;
  final String name;

  const BridgeWeek({
    required this.startDate,
    required this.endDate,
    required this.term,
    required this.curWeek,
    required this.serialNumber,
    required this.name,
  });

  @override
  int get hashCode =>
      startDate.hashCode ^
      endDate.hashCode ^
      term.hashCode ^
      curWeek.hashCode ^
      serialNumber.hashCode ^
      name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeWeek &&
          runtimeType == other.runtimeType &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          term == other.term &&
          curWeek == other.curWeek &&
          serialNumber == other.serialNumber &&
          name == other.name;
}

class BridgeWeeklySchedule {
  final List<BridgeCourseClass> arrangedList;
  final String code;
  final String name;
  final List<BridgeSectionTime> sectionTimes;

  const BridgeWeeklySchedule({
    required this.arrangedList,
    required this.code,
    required this.name,
    required this.sectionTimes,
  });

  @override
  int get hashCode =>
      arrangedList.hashCode ^
      code.hashCode ^
      name.hashCode ^
      sectionTimes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeWeeklySchedule &&
          runtimeType == other.runtimeType &&
          arrangedList == other.arrangedList &&
          code == other.code &&
          name == other.name &&
          sectionTimes == other.sectionTimes;
}

class BridgeYgdkItem {
  final int itemId;
  final String name;
  final int? kind;
  final int? sort;
  final BridgeActionEligibility submitEligibility;
  final BridgeYgdkSubmitTarget? submitTarget;

  const BridgeYgdkItem({
    required this.itemId,
    required this.name,
    this.kind,
    this.sort,
    required this.submitEligibility,
    this.submitTarget,
  });

  @override
  int get hashCode =>
      itemId.hashCode ^
      name.hashCode ^
      kind.hashCode ^
      sort.hashCode ^
      submitEligibility.hashCode ^
      submitTarget.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeYgdkItem &&
          runtimeType == other.runtimeType &&
          itemId == other.itemId &&
          name == other.name &&
          kind == other.kind &&
          sort == other.sort &&
          submitEligibility == other.submitEligibility &&
          submitTarget == other.submitTarget;
}

class BridgeYgdkOverview {
  final BridgeYgdkTermSummary summary;
  final int classifyId;
  final String classifyName;
  final int defaultItemId;
  final String defaultItemName;
  final List<BridgeYgdkItem> items;

  const BridgeYgdkOverview({
    required this.summary,
    required this.classifyId,
    required this.classifyName,
    required this.defaultItemId,
    required this.defaultItemName,
    required this.items,
  });

  @override
  int get hashCode =>
      summary.hashCode ^
      classifyId.hashCode ^
      classifyName.hashCode ^
      defaultItemId.hashCode ^
      defaultItemName.hashCode ^
      items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeYgdkOverview &&
          runtimeType == other.runtimeType &&
          summary == other.summary &&
          classifyId == other.classifyId &&
          classifyName == other.classifyName &&
          defaultItemId == other.defaultItemId &&
          defaultItemName == other.defaultItemName &&
          items == other.items;
}

class BridgeYgdkRecord {
  final int recordId;
  final int? itemId;
  final String? itemName;
  final String? startTime;
  final String? endTime;
  final String? place;
  final int imageCount;
  final bool isOpen;
  final int? state;
  final String? createdAt;
  final String? createdAtLabel;

  const BridgeYgdkRecord({
    required this.recordId,
    this.itemId,
    this.itemName,
    this.startTime,
    this.endTime,
    this.place,
    required this.imageCount,
    required this.isOpen,
    this.state,
    this.createdAt,
    this.createdAtLabel,
  });

  @override
  int get hashCode =>
      recordId.hashCode ^
      itemId.hashCode ^
      itemName.hashCode ^
      startTime.hashCode ^
      endTime.hashCode ^
      place.hashCode ^
      imageCount.hashCode ^
      isOpen.hashCode ^
      state.hashCode ^
      createdAt.hashCode ^
      createdAtLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeYgdkRecord &&
          runtimeType == other.runtimeType &&
          recordId == other.recordId &&
          itemId == other.itemId &&
          itemName == other.itemName &&
          startTime == other.startTime &&
          endTime == other.endTime &&
          place == other.place &&
          imageCount == other.imageCount &&
          isOpen == other.isOpen &&
          state == other.state &&
          createdAt == other.createdAt &&
          createdAtLabel == other.createdAtLabel;
}

class BridgeYgdkRecordsPage {
  final List<BridgeYgdkRecord> content;
  final int total;
  final int page;
  final int size;
  final bool hasMore;

  const BridgeYgdkRecordsPage({
    required this.content,
    required this.total,
    required this.page,
    required this.size,
    required this.hasMore,
  });

  @override
  int get hashCode =>
      content.hashCode ^
      total.hashCode ^
      page.hashCode ^
      size.hashCode ^
      hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeYgdkRecordsPage &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          total == other.total &&
          page == other.page &&
          size == other.size &&
          hasMore == other.hasMore;
}

class BridgeYgdkSubmitTarget {
  final int classifyId;
  final int itemId;

  const BridgeYgdkSubmitTarget({
    required this.classifyId,
    required this.itemId,
  });

  @override
  int get hashCode => classifyId.hashCode ^ itemId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeYgdkSubmitTarget &&
          runtimeType == other.runtimeType &&
          classifyId == other.classifyId &&
          itemId == other.itemId;
}

class BridgeYgdkTermSummary {
  final int? termId;
  final String? termName;
  final int termCount;
  final int? termTarget;
  final int? weekCount;
  final int? weekTarget;
  final int? monthCount;
  final int? monthTarget;
  final int? dayCount;
  final int? goodCount;

  const BridgeYgdkTermSummary({
    this.termId,
    this.termName,
    required this.termCount,
    this.termTarget,
    this.weekCount,
    this.weekTarget,
    this.monthCount,
    this.monthTarget,
    this.dayCount,
    this.goodCount,
  });

  @override
  int get hashCode =>
      termId.hashCode ^
      termName.hashCode ^
      termCount.hashCode ^
      termTarget.hashCode ^
      weekCount.hashCode ^
      weekTarget.hashCode ^
      monthCount.hashCode ^
      monthTarget.hashCode ^
      dayCount.hashCode ^
      goodCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeYgdkTermSummary &&
          runtimeType == other.runtimeType &&
          termId == other.termId &&
          termName == other.termName &&
          termCount == other.termCount &&
          termTarget == other.termTarget &&
          weekCount == other.weekCount &&
          weekTarget == other.weekTarget &&
          monthCount == other.monthCount &&
          monthTarget == other.monthTarget &&
          dayCount == other.dayCount &&
          goodCount == other.goodCount;
}
