name: ubaa_ui
description: UBAA 跨平台共享 Material 3 UI。
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  ubaa_domain:
    path: ../ubaa_domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  ubaa_app:
    path: ../ubaa_app

flutter:
  assets:
    - assets/libbook/
